### ISSUE TITLE
npm run dev 编译不通过

### ISSUE THREAD

**Issue by zzlw** [vincentSea/gulp-demo#5]
```

      -----------------------------
[16:49:46] Starting 'html'...
[16:49:46] Starting 'styles'...
[16:49:46] Starting 'script'...
[16:49:46] Starting 'images'...
[16:49:46] gulp-notify: [undefined Error] write callback called multiple times
[16:49:46] gulp-notify: [undefined Error] write callback called multiple times
[16:49:46] Finished 'images' after 211 ms
[16:49:46] Finished 'script' after 295 ms

events.js:165
      throw er; // Unhandled 'error' event
      ^
Error: spawn /Users/andy/Desktop/gulp-cli/node_modules/_optipng-bin@3.1.4@optipng-bin/vendor/optipng ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:379:16)
    at process._tickCallback (internal/process/next_tick.js:114:19)
Emitted 'error' event at:
    at Immediate.<anonymous> (/Users/andy/Desktop/gulp-cli/node_modules/_through2-concurrent@1.1.1@through2-concurrent/through2-concurrent.js:37:14)
    at runCallback (timers.js:764:11)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate (timers.js:716:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gulpcli@2.0.0 dev: `gulp server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gulpcli@2.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by scarecrowdu** [comment]
是否全局安装了gulp？

`
npm install -g gulp
`
